# -*- coding: utf-8 -*-
"""HTML_QUICK_STYLER_PRO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fNqYte4oKAtNZXM5TY9EDDLmWR38KGb
"""

!pip install gradio transformers torch

class ColorPaletteGenerator:

    def __init__(self):

        self.palettes = {

            "modern": {
                "primary": "#6366F1",
                "secondary": "#8B5CF6",
                "accent": "#EC4899",
                "background": "#0F172A",
                "surface": "#1E293B",
                "text": "#F8FAFC"
            },

            "ocean": {
                "primary": "#0EA5E9",
                "secondary": "#06B6D4",
                "accent": "#22D3EE",
                "background": "#082F49",
                "surface": "#0C4A6E",
                "text": "#F0F9FF"
            },

            "forest": {
                "primary": "#16A34A",
                "secondary": "#22C55E",
                "accent": "#4ADE80",
                "background": "#052E16",
                "surface": "#14532D",
                "text": "#ECFDF5"
            }

        }

    def get_palette(self, style):

        return self.palettes.get(style, self.palettes["modern"])

class HTMLPageBuilder:

    def hero_section(self, title):

        return f"""
        <section class='hero'>
            <h1>{title}</h1>
            <p>Welcome to our website generated with HTML Quick Styler.</p>
            <button>Get Started</button>
        </section>
        """

    def about_section(self):

        return """
        <section class='about'>
            <h2>About Us</h2>
            <p>This page was automatically generated using AI powered HTML Quick Styler.</p>
        </section>
        """

    def portfolio_section(self):

        return """
        <section class='portfolio'>
            <h2>Portfolio</h2>
            <div class='grid'>
                <div class='card'>Project 1</div>
                <div class='card'>Project 2</div>
                <div class='card'>Project 3</div>
            </div>
        </section>
        """

    def contact_section(self):

        return """
        <section class='contact'>
            <h2>Contact Us</h2>
            <input placeholder='Name'>
            <input placeholder='Email'>
            <textarea placeholder='Message'></textarea>
            <button>Send</button>
        </section>
        """

def generate_css(palette):

    return f"""

    body {{
        font-family: Arial, sans-serif;
        background:{palette['background']};
        color:{palette['text']};
        margin:0;
        padding:0;
    }}

    .hero {{
        padding:80px;
        text-align:center;
        background: linear-gradient(45deg, {palette['primary']}, {palette['secondary']});
    }}

    .hero button {{
        padding:12px 25px;
        border:none;
        background:{palette['accent']};
        color:white;
        border-radius:5px;
        font-size:16px;
    }}

    section {{
        padding:60px;
    }}

    .grid {{
        display:grid;
        grid-template-columns:repeat(3,1fr);
        gap:20px;
    }}

    .card {{
        padding:30px;
        background:{palette['surface']};
        border-radius:10px;
        text-align:center;
    }}

    input, textarea {{
        display:block;
        margin:10px 0;
        padding:10px;
        width:300px;
    }}

    button {{
        cursor:pointer;
    }}

    """

def generate_page(title, description, style):

    palette = ColorPaletteGenerator().get_palette(style)

    builder = HTMLPageBuilder()

    html = ""

    description = description.lower()

    if "hero" in description:
        html += builder.hero_section(title)

    if "about" in description:
        html += builder.about_section()

    if "portfolio" in description:
        html += builder.portfolio_section()

    if "contact" in description:
        html += builder.contact_section()

    css = generate_css(palette)

    full_page = f"""
    <html>

    <style>
    {css}
    </style>

    <body>
    {html}
    </body>

    </html>
    """

    return full_page

import gradio as gr

# HTML generator with dynamic styles
def generate_html(title, description, style):
    bg_color = "#0f172a"
    text_color = "#ffffff"
    btn_color = "#ec4899"
    font = "Poppins"

    hero_bg = bg_color
    card_bg = "#1e293b"
    if style == "modern":
        hero_bg = f"linear-gradient(45deg, {bg_color}, #8b5cf6)"
        card_bg = "#1e293b"
    elif style == "dark":
        hero_bg = "#1e293b"
        card_bg = "#111827"
    elif style == "minimal":
        hero_bg = bg_color
        card_bg = "#f1f5f9"

    style_css = f"""
    body {{
        font-family: '{font}', sans-serif;
        background:{bg_color};
        color:{text_color};
        margin:0;
        padding:40px;
        text-align:center;
    }}
    .hero {{
        background:{hero_bg};
        padding:60px;
        border-radius:12px;
        color:{text_color};
    }}
    .btn {{
        background:{btn_color};
        padding:12px 24px;
        border:none;
        color:white;
        border-radius:6px;
        margin-top:20px;
        font-size:16px;
        cursor:pointer;
    }}
    .card {{
        background:{card_bg};
        color:{text_color};
        padding:20px;
        border-radius:10px;
        width:220px;
        height:150px;
        display:flex;
        flex-direction:column;
        justify-content:center;
        transition: transform 0.2s, box-shadow 0.2s;
        text-align:center;
        margin:auto;
    }}
    .card:hover {{
        transform: scale(1.05);
        box-shadow: 0px 5px 15px rgba(0,0,0,0.3);
    }}
    .portfolio {{
        display:flex;
        flex-wrap:wrap;
        justify-content:center;
        gap:20px;
        margin-top:20px;
    }}
    .palette {{
        background:#1e293b;
        color:white;
        padding:20px;
        border-radius:10px;
        text-align:center;
        cursor:pointer;
        transition: transform 0.2s, box-shadow 0.2s;
        width:150px;
        margin:auto;
    }}
    .palette:hover {{
        transform: scale(1.05);
        box-shadow: 0px 5px 15px rgba(0,0,0,0.3);
    }}
    """

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <title>{title}</title>
    <link href="https://fonts.googleapis.com/css2?family={font.replace(' ', '+')}&display=swap" rel="stylesheet">
    <style>{style_css}</style>
    </head>
    <body>
    <div class="hero">
        <h1>{title}</h1>
        <p>{description}</p>
        <button class="btn">Get Started</button>
    </div>
    <div class="section">
        <h2>Example Templates</h2>
        <div class="portfolio">
            <div class="card">
                <h3>Basic Webpage</h3>
                <p>A simple styled webpage layout.</p>
            </div>
            <div class="card">
                <h3>Portfolio Layout</h3>
                <p>Clean design for projects showcase.</p>
            </div>
            <div class="card">
                <h3>Landing Page</h3>
                <p>Modern page for product or service.</p>
            </div>
        </div>
    </div>
    </body>
    </html>
    """
    return html

# Template autofill
def use_template(template):
    if template == "portfolio":
        return "My Portfolio", "Welcome to my portfolio where I showcase my projects."
    elif template == "startup":
        return "Startup Landing Page", "Discover our innovative product designed to change the future."
    elif template == "blog":
        return "My Personal Blog", "Thoughts, tutorials, and stories from my journey."
    return "", ""

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🎨 HTML Quick Styler Pro")
    gr.Markdown("Generate styled HTML pages with code output and live preview.")

    html_state = gr.State("")

    with gr.Tabs():

        # Generate Page Tab
        with gr.Tab("Generate Page"):
            title = gr.Textbox(label="Page Title")
            description = gr.Textbox(label="Page Description")
            style = gr.Dropdown(["modern","dark","minimal"], value="modern", label="Style Theme")

            generate_btn = gr.Button("✨ Generate HTML")
            output_code = gr.Code(label="Generated HTML/CSS Code", language="html")

            generate_btn.click(
                lambda t, d, s: (generate_html(t,d,s), generate_html(t,d,s)),
                inputs=[title, description, style],
                outputs=[output_code, html_state]
            )

        # Live Preview Tab
        with gr.Tab("Live Preview"):
            gr.Markdown("### Click the button below to load the generated page")
            load_btn = gr.Button("Load Preview")
            live_preview = gr.HTML(label="Website Preview")
            load_btn.click(lambda html: html, inputs=html_state, outputs=live_preview)

        # Templates Tab
        with gr.Tab("Templates"):
            gr.Markdown("### Quick Templates")
            with gr.Row():
                for name, desc, key in [("Portfolio","Showcase your projects in a clean layout.","portfolio"),
                                        ("Startup","Modern landing page for your innovative product.","startup"),
                                        ("Blog","Share your thoughts, tutorials, and stories.","blog")]:
                    with gr.Column(scale=1):
                        gr.HTML(f'<div class="card"><h3>{name}</h3><p>{desc}</p></div>')
                        btn = gr.Button("Use Template")
                        btn.click(lambda k=key: use_template(k), outputs=[title, description])

        # Color Palettes Tab
        with gr.Tab("Color Palettes"):
            gr.Markdown("### Click 'Get Palette' to apply a style")
            with gr.Row():
                for palette_name, label in [("modern","🎨 Modern<br>Purple gradient modern design."),
                                            ("dark","🌙 Dark<br>Dark UI with minimal highlights."),
                                            ("minimal","⚪ Minimal<br>Clean and simple light theme.")]:
                    with gr.Column(scale=1):
                        gr.HTML(f'<div class="palette">{label}</div>')
                        btn = gr.Button("Get Palette")
                        btn.click(lambda n=palette_name: n, outputs=style)

        # Guide Tab (UPDATED)
        with gr.Tab("Guide"):
            gr.HTML("""
            <div style="background:#1e293b; padding:30px; border-radius:12px; color:white; max-width:600px; margin:auto;">
              <h2 style="text-align:center; margin-bottom:20px;">📖 How to Use HTML Quick Styler</h2>

              <div style="display:flex; align-items:flex-start; margin-bottom:15px;">
                <div style="flex-shrink:0; width:30px; height:30px; border-radius:50%; background:#ec4899; display:flex; align-items:center; justify-content:center; font-weight:bold; margin-right:10px;">1</div>
                <div>Enter your <b>Page Title</b> and <b>Page Description</b>.</div>
              </div>

              <div style="display:flex; align-items:flex-start; margin-bottom:15px;">
                <div style="flex-shrink:0; width:30px; height:30px; border-radius:50%; background:#ec4899; display:flex; align-items:center; justify-content:center; font-weight:bold; margin-right:10px;">2</div>
                <div>Choose a <b>Style Theme</b> from the dropdown.</div>
              </div>

              <div style="display:flex; align-items:flex-start; margin-bottom:15px;">
                <div style="flex-shrink:0; width:30px; height:30px; border-radius:50%; background:#ec4899; display:flex; align-items:center; justify-content:center; font-weight:bold; margin-right:10px;">3</div>
                <div>Click the <b>Generate HTML</b> button to create your page.</div>
              </div>

              <div style="display:flex; align-items:flex-start; margin-bottom:15px;">
                <div style="flex-shrink:0; width:30px; height:30px; border-radius:50%; background:#ec4899; display:flex; align-items:center; justify-content:center; font-weight:bold; margin-right:10px;">4</div>
                <div>Copy the <b>Generated HTML/CSS Code</b> from the output box.</div>
              </div>

              <div style="display:flex; align-items:flex-start;">
                <div style="flex-shrink:0; width:30px; height:30px; border-radius:50%; background:#ec4899; display:flex; align-items:center; justify-content:center; font-weight:bold; margin-right:10px;">5</div>
                <div>Go to the <b>Live Preview</b> tab and click <b>Load Preview</b> to view your website live.</div>
              </div>
            </div>
            """)

demo.launch(share=True)